### ISSUE TITLE
Some recitations are not shown as available

### ISSUE THREAD

**Issue by aliberman99** [64json/gt-scheduler#1]
For example, for CHEM 1310, the page is only letting my select lecture C (which is the only one available for Spring 19) and recitation C06 (many of which are available for Spring 19). If I manually select any other recitation, I have no possible class schedules. Am I doing something wrong?

**Comment by 64json** [comment]
The fixed version has just been deployed. It should be working properly after refreshing or clearing browser cache. Thank you for reporting the issue!
