### ISSUE TITLE
Missing copyright notice

### ISSUE THREAD

**Issue by karpawich** [64json/gt-scheduler#17]
In order for Bits of Good to properly provide a copyright notice on [their fork](https://github.com/GTBitsOfGood/gt-scheduler) per the terms of the AGPL license, we ask that a corresponding notice be explicitly provided on the original repo, such that the terms of AGPL are formally met.

TLDR is that in order to provide a copy of a copyright notice, we just ask that it copy-able

**Comment by 64json** [comment]
I don't think it is necessary to have a copyright notice on the original repo. I found a [discussion](https://github.com/github/opensource.guide/issues/341) about it, which might be worthwhile to read.
