### ISSUE TITLE
Incomplete set of classes.

### ISSUE THREAD

**Issue by abrahimladha** [64json/gt-scheduler#2]
Some classes are missing. For example Fall 2019, CS 8803 has only 8 courses. Courseff is showing me 13, and Oscar is showing me 15.

**Comment by 64json** [comment]
Hi @abrahimladha, CS 8803 does have all the 15 sections. The reason it's showing only 8 combinations is that sections with the same time slots are regarded as one.

<img width="517" alt="Screen Shot 2019-07-07 at 8 10 16 AM" src="https://user-images.githubusercontent.com/1618732/60761945-bc82ce00-a08e-11e9-9cad-2cf486aa0c1f.png">

I understand it can be confusing, so I will try to fix it when I get time. Thanks!

**Comment by abrahimladha** [comment]
User issue haha. Thanks for your communication.
